const dummyLeads = [
  {
    _id: "1",
    firstName: "Vikas",
    lastName: "Sharma",
    email: "vikas@example.com",
    phone: "9999999999",
    city: "Jaipur",
    country: "India",
    status: "All",
    title: "Website Redesign",
    closureDate: "2025-07-01",
    createdAt: "2025-06-01",
    stage: "Qualified",
    estimatedWorth: "$10,000",
    organizationName: "DesignCo",
    organizationEmail: "info@designco.com",
    organizationPhone: "1234567890",
  },
  {
    _id: "2",
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya@example.com",
    phone: "8888888888",
    city: "Delhi",
    country: "India",
    status: "Hold",
    title: "CRM Integration",
    closureDate: "2025-07-10",
    createdAt: "2025-06-03",
    stage: "Contacted",
    estimatedWorth: "$8,000",
    organizationName: "SalesConnect",
    organizationEmail: "contact@salesconnect.com",
    organizationPhone: "2345678901",
  },
  {
    _id: "3",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    phone: "7777777777",
    city: "Mumbai",
    country: "India",
    status: "Lost",
    title: "Mobile App Development",
    closureDate: "2025-07-15",
    createdAt: "2025-06-05",
    stage: "Proposal Sent",
    estimatedWorth: "$15,000",
    organizationName: "Appify",
    organizationEmail: "hello@appify.com",
    organizationPhone: "3456789012",
  },
  {
    _id: "4",
    firstName: "Ravi",
    lastName: "Verma",
    email: "ravi@example.com",
    phone: "6666666666",
    city: "Hyderabad",
    country: "India",
    status: "Deleted",
    title: "E-commerce Platform",
    closureDate: "2025-07-20",
    createdAt: "2025-06-07",
    stage: "Lost",
    estimatedWorth: "$12,000",
    organizationName: "ShopEase",
    organizationEmail: "support@shopease.com",
    organizationPhone: "4567890123",
  },
];

export default dummyLeads;